workspace_size: [100,100] # (m) [x,y] Size of the workspace/room where the robot needs to navigate
grid_resolution: 0.1    # (m) The distance between two neighboring cells 
drawing_brush_size: 5   # (m) How big the drawing brash will be
robot_size: 1           # (m) How much the walls are going to be inflated
occupancy_grid_filename: "null" # The file name of the occupancy grid you want to save (WITHOUT FILE EXTENSION)
